version: '3'
services:
 nginx:
   container_name: v-nginx
   image: nginx:1.13
   restart: always
   ports:
      - 801:80
      - 444:443
   volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
 mysql:
   container_name: v-mysql
   image: mysql/mysql-server:5.7
   environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
   ports:
      - "3307:3306"
   restart: always
 app:
   restart: always
   build: ./app
   working_dir: /app
   volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
   # expose:
   #  - "9527"
   ports:
      - "9527:9527"
   depends_on:
      - nginx
      - mysql
   command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker
